databases:
  - name: orbit-db
    plan: free
    databaseName: orbit
    user: orbit

services:
  - type: web
    name: orbit
    runtime: docker
    plan: free
    healthCheckPath: /login
    envVars:
      - key: APP_NAME
        value: "Orbit ☕️"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: "https://REPLACE-WITH-YOUR-RENDER-URL.onrender.com"
      - key: APP_LOCALE
        value: en
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: orbit-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: BROADCAST_CONNECTION
        value: log
      - key: FILESYSTEM_DISK
        value: local
      - key: FREE_MODE
        value: "true"
      - key: MAIL_MAILER
        value: resend
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM_ADDRESS
        value: "onboarding@resend.dev"
      - key: MAIL_FROM_NAME
        value: "Orbit ☕️"
      - key: GROQ_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: ADMIN_NAME
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
